Script reso invocabile da qualsiasi percorso
Prima:

✔ /tmp/fv [fix_invocazione L|✔]
12:51 $ bash scripts/genera_pdf_VG_VT_CV.sh
|| Starting conversion for versione_generale (VG) ||
Pdf files generating...
QPainter::begin(): Returned false
QPainter::begin(): Returned false
Pdf files generated.
Png files generating...
Loading page (1/2)
Rendering (2/2)
Error: Could not write to output file
Error: Could not save image
Done
Exit with code 1, due to unknown error.

Dopo:

✔ /tmp/fv [fix_invocazione L|✚ 1]
12:55 $ /tmp/fv/scripts/genera_pdf_VG_VT_CV.sh
|| Starting conversion for versione_generale (VG) ||
Pdf files generating...
Pdf files generated.
Png files generating...
Loading page (1/2)
Rendering (2/2)
Done
Loading page (1/2)
Rendering (2/2)
Done
Png files generated.
Pdf files merging in a single pdf file...
Pdf merged correctly.
Temp files deleting...
Temp files deleted.
|| Completed conversion for version VG ||
|| Starting conversion for versione_tecnica (VT) ||
Pdf files generating...
Pdf files generated.
Png files generating...
Loading page (1/2)
Rendering (2/2)
Done
Loading page (1/2)
Rendering (2/2)
Done
Png files generated.
Pdf files merging in a single pdf file...
Pdf merged correctly.
Temp files deleting...
Temp files deleted.
|| Completed conversion for version VT ||
|| Completed all conversions ||
------------------------
Details:
NAME: Vademecum
VERSION: 2.0
VERSION TYPES GENERATED:
| VG:
| | Vademecum_2.0_VG_fronte.png
| | Vademecum_2.0_VG_retro.png
| | Vademecum_2.0_VG.pdf
| VT:
| | Vademecum_2.0_VT_fronte.png
| | Vademecum_2.0_VT_retro.png
| | Vademecum_2.0_VT.pdf
------------------------